caddy_version: v2.0.0-beta.19
caddy_filename_prefix: caddy2_beta19
# sha256 checksums for github-released binaries
checksums:
  amd64: 8e44c8f801fd01f544738767af4ea76359dca17718d1aafcfa893ea45a837736
  arm64v8: 2b938c63863d32c3e384d4a32d387b553623514f1ca6860574ca35bfe5c6e4c1
# configuration for the stackbrew.tmpl template
variants:
  - dir: alpine
    tags: [ "{{.conf.caddy_version | strings.TrimPrefix `v` }}", "{{.conf.caddy_version | strings.TrimPrefix `v` }}-alpine", "alpine", "latest" ]
    architectures: [ amd64 ]
  # Drop this for now!
  # - dir: scratch
  #   tags: [ "{{.conf.caddy_version}}-slim", "scratch" ]
  #   architectures: [ amd64 ]
  - dir: builder
    tags: [ "{{.conf.caddy_version | strings.TrimPrefix `v` }}-builder", "builder" ]
    architectures: [ amd64 ]
