caddy_version: 2.0.0-rc.3
# sha256 checksums for github-released binaries
checksums:
  amd64: 32735a963f946bf561ed2a540192c22ad19565be4bce4bc243c61beae9022ca15a54bf5ef8a5f2341bd3af16fd7b0e9f7832697687201a981a2ac52b0c18ca88
  arm64v8: c4786c030121519ea988ad418878f29b90487357bb434f357955a5ac158460192b4da136fd6d08a2507521a2920412ffa294bf2d83c858c3d1e7fb02de1482a2
# configuration for the stackbrew.tmpl template
variants:
  - dir: alpine
    tags: [ "{{.conf.caddy_version}}", "{{.conf.caddy_version}}-alpine", "alpine", "latest" ]
    architectures: [ amd64 ]
  # Drop this for now!
  # - dir: scratch
  #   tags: [ "{{.conf.caddy_version}}-slim", "scratch" ]
  #   architectures: [ amd64 ]
  - dir: builder
    tags: [ "{{.conf.caddy_version}}-builder", "builder" ]
    architectures: [ amd64 ]
